services:
  immich-server:
    image: reg.g5d.dev/immich:latest
    volumes:
      - data:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      UPLOAD_LOCATION: "/usr/src/app/upload"
      TZ: "Europe/London"
      DB_USERNAME: immich
      DB_DATABASE_NAME: immich
      DB_PASSWORD: immich
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: unless-stopped

  redis:
    image: docker.io/redis:6.2-alpine
    restart: unless-stopped

  database:
    image: docker.io/tensorchord/pgvecto-rs:pg16-v0.3.0
    environment:
      POSTGRES_PASSWORD: immich
      POSTGRES_USER: immich
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - database:/var/lib/postgresql/data
    restart: unless-stopped
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]

volumes:
  data:
  database:
