on:
  workflow_dispatch:
  schedule:
    - cron: '33 12 * * *'
  push:
    paths-ignore:
      - '**/Containerfile'
      - '**/Dockerfile'
      - '.github/**'
      - 'READNE.md'
      - 'bootstrap.sh'
name: update
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@master
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - name: Login to private registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
      - name: Login to mirror target registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CONTEMPT_TOKEN }}
      - name: Update dockerfiles
        env:
          REGISTRY: ${{ secrets.REGISTRY }}
          MIRROR_TARGET: ghcr.io
          MIRROR_PATH: ${{ github.repository }}
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          REPO_OWNER: ${{ github.repository_owner }}
          REG_USER: ${{ secrets.REGISTRY_USER }}
          REG_PASS: ${{ secrets.REGISTRY_PASS }}
          CONTEMPT_TOKEN: ${{ secrets.CONTEMPT_TOKEN }}
          SOURCE_LINK: https://github.com/greboid/dockerfiles/blob/master/
        run:  |
          echo "Running contempt"
          "${GITHUB_WORKSPACE}/.github/contempt.sh"
          echo "Mirroring images"
          "${GITHUB_WORKSPACE}/.github/mirror.sh"
